### ISSUE TITLE
Enhanced login process

### ISSUE THREAD

**Issue by paulgessinger** [paulgessinger/swift-paperless#10]
Right now the app requires to put in a valid public API URL, username and password to get an auth token. 

If at all possible it would be nicer if the app could simply throw up a browser window with the login URL, the user logs in and the app fetches the token from a redirect.

See

- https://github.com/paperless-ngx/paperless-ngx/discussions/3283#discussioncomment-5955103
- https://github.com/paperless-ngx/paperless-ngx/discussions/3283#discussioncomment-5946161
- https://developer.apple.com/documentation/authenticationservices/authenticating_a_user_through_a_web_service

**Comment by paulgessinger** [comment]
So as far as I understand it, Authelia uses session cookies to pass through clients to the upstream app, while at the same time providing the app with some trusted identity.

I don't think I'd be able to grab these cookies from an isolated webview at all, and even then I'd have to grab ALL cookies and always send them with all API requests, which I'm not sure is something the app should do.

OTOH, as far as I understand it, excluding `/api` from Authelia might be acceptable, other applications seem to have this same issue with Authelia, and I've seen this approach recommended. This could be combined with a "nice" way of grabbing the token through a webview.

Thoughts @hendrik1120, @RefineryX?

**Comment by hendrik1120** [comment]
Yes, you can't get the authelia cookies. These two issues are acutally **not** related, I was about to comment about that.
@RefineryX you actually need to bypass the api, there is no other way. Since you can authenticate against the api your authelia protection is now limited to vulnerabilities in the paperless login form/site not api endpoint.

My issue is more about the general login into paperless. If they change or add other authentication methods like oidc the app can't use any of that. I am pretty sure that you can get the django session cookie from paperless, but this needs some work from the maintainers to return it in the request for you. Like nextcloud you could then basically install any auth plugin and all apps would still work.
In my case, authelia is basically bypassed but still handles authentication via the back channel.

**Comment by paulgessinger** [comment]
Ok, understood and agreed. 

Indeed there would need to be some way to obtain the token via redirect after a web-based login to paperless. I don't currently have bandwidth to try to add this to paperless itself, but I agree this would be excellent, especially if OIDC gets merged!

**Comment by sceiler** [comment]
Please also consider the cases where people have no password setup

**Comment by awahlig** [comment]
+1

I’m using the Remote User Auth with Tailscale (a VPN). Since I need to authenticate with Tailscale to reach the server at all, Tailscale can tell Paperless who I am. Works great on the website and in API calls.

**Comment by paulgessinger** [comment]
@awahlig can you give more details on your setup? From what I can tell this could work without an extra auth flow, it would be enough to just not send a token. 

I also use Tailscale, maybe I can try this out.

**Comment by awahlig** [comment]
Yes, I think this should work. You’d also need to tweak the UI to allow empty login/password fields.

Here’s my setup:

I’m using [tailscale serve](https://tailscale.com/kb/1242/tailscale-serve) to expose paperless to the tailnet. It alse takes care of https termination and adds identity headers to all requests, as described [here](https://tailscale.com/kb/1312/serve#identity-headers).

The paperless docker container is then configured as follows:

```
environment:
      # Tailscale authorization
      PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
      PAPERLESS_ENABLE_HTTP_REMOTE_USER_API: "true"
      PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_TAILSCALE_USER_LOGIN
```

The user login that Tailscale provides is your email address so the name of Paperless user needs to be the same.

In my case, tailscale and tailscale serve are running in a dedicated container but it should work just as well if you run it on the host. Using a container allows me to have Paperless as a separate machine on the tailnet.

Since this is different than what OP asked about, should we create a new issue to discuss further?

**Comment by hendrik1120** [comment]
Hi, thanks for developing and maintaining this app. I use it very often. Since the last time looking at this, OpenID connect has finally been implemented in paperless using django-allauth.
Since django-allauth brings a lot of features including the https://docs.allauth.org/en/latest/headless/index.html headless api, it should now be much easier to integrate the default paperless authentication flow into your app including oidc and future MFA.

**Comment by paulgessinger** [comment]
@hendrik1120 this is true. Actually, there's a separate issue #50 that I'll actually close this one in favor of (has more activity) about this. 

I think the main problem (and if you know otherwise please let me know), the issue is still that for OIDC with a third-party login, we would need Paperless-ngx to accept the third-party tokens to authenticate to the API. 

Afaik, this is not currently implemented in Paperless-ngx.

If this moves forward, and Paperless-ngx ends up allowing login directly via third-party tokens, I believe we have a solution for this.
