### ISSUE TITLE
Tasks error

### ISSUE THREAD

**Issue by SoCuul** [paulgessinger/swift-paperless#107]
I think a bit of example code might have been left in the App Store version of the app, as in the logs I can see requests requesting (and failing) to go to example.com

![image](https://github.com/paulgessinger/swift-paperless/assets/63339559/c2e8b02e-d438-42d7-9eb2-d2f3863c0050)

**Comment by SoCuul** [comment]
Oops forgot to assign the bug tag to this one 😅

**Comment by paulgessinger** [comment]
Hey @SoCuul, this is actually intentional. 

I'm replacing the actual URL of the instance with `example.com`, so that when people share logs they don't leak their instance URL accidentally.

The reason this "error" pops up (as far as I know) is that when a view appears, it triggers a request to load some data. When the view disappears, the task that was launched for this is still active, and gets canceled by SwiftUI. The logging picks up these errors. I guess I should probably suppress these errors in the logs.

**Comment by SoCuul** [comment]
Maybe for clarity don't remove the logs, but just put something like `censored-by-swiftpaperless` instead of `example.com`

**Comment by paulgessinger** [comment]
I'm working to suppress the cancellation errors as much as possible now, since they're not actually errors. 

Other than that, I'll close this issue for now.
