### ISSUE TITLE
Self signed certificate not accepted

### ISSUE THREAD

**Issue by apfelnutzer** [paulgessinger/swift-paperless#141]
I host paperless ngx locally and use Traefik to provide https access to it. Everything works fine in the browser, but the app does not accept my self signed certificate although I imported and trusted it on my iPhone.

![image](https://github.com/user-attachments/assets/b0ece1e0-23a9-4970-b360-5f36e550b803)

**Comment by apfelnutzer** [comment]
... a quick workaround could be to allow login in anyway - current the login button is deactivated.

**Comment by paulgessinger** [comment]
Hi!

See https://github.com/paulgessinger/swift-paperless/issues/109 for previous discussion on this topic. 

It's possible to work with self signed certificates using the OS trust store. 

Certificates ostensibly need to use a CA, rather than using the CA cert directly, their lifetime needs to be short enough, and they need to be properly configured for your domain. 

Anything else leads to certificate errors, which I can't really provide better error messaging for. 

Not allowing certificates rejected by the OS networking layer is a security decision, and I currently do not intend to change this.

**Comment by apfelnutzer** [comment]
Hi,

thank for your quick response! Following your hints I was able to make this work, too. I was using the CA cert directly and it was valid for ten years...

Best regards,
Sebastian
