### ISSUE TITLE
Improve document editing UI to allow referencing the document while editing

### ISSUE THREAD

**Issue by Se7enair** [paulgessinger/swift-paperless#52]
So far the best app for paperless. Very good work.

But there is one thing I don’t like. If I edit a document, I only see the document in the background. So I cannot check for example the date on the document. 

It would be nice if I can edit the details in the document view and don’t need the popup.

**Comment by paulgessinger** [comment]
Hey @Se7enair, 

I've also been thinking about this (and have this issue myself).
I was thinking I might change the interface so that either the document view can slide over the main view of the document, or the other way round, where the edit view slides over the document itself.

In both cases, you would then be able to swipe the overlaid view up and down (a little bit like in mail) and could take a peek.

One complication is that building a custom PDF view with zooming etc is not *fun*. I can use the system provided PDF view, which allows zooming and so on, but I've found it to be fiddly, and much worse than the quicklook view that currently opens when you tap on the document preview now.

**Comment by Se7enair** [comment]
Sounds good that I am not alone with this problem.

How about expanding the header in the document view to edit details?
