### ISSUE TITLE
Authorizations are not applied correctly

### ISSUE THREAD

**Issue by thegodfatherrelish** [paulgessinger/swift-paperless#60]
First of all: I'm not sure if this is a problem with the app or with Paperless-ngx, but the permissions of the documents are not taken into account when they are displayed in the app.

If I log in with my normal user without admin rights, who should only have access to his documents, I am still shown documents that are explicitly assigned to only one other person as the owner. Everything is displayed correctly in the browser.

Is this a bug within the app or should I also open an issue with Paperless-ngx because the rights are apparently not assigned so robustly that the behavior can occur?

**Addendum**: The whole thing occurs under iOS 17.3.1, both under the last stable version and in the version currently published by TestFlight.

@shamoon: FYI

**Comment by paulgessinger** [comment]
I wouldn't preclude the app not doing exactly the right thing, but at the end of the day, the API should not return documents that shouldn't be visible to logged in user, I would argue.

That being said, I have not thoroughly tested the app with multiple users and permissions, simply because I don't personally use these features.

**Comment by paulgessinger** [comment]
Not imminently, but it is on my roadmap!

**Comment by paulgessinger** [comment]
Closing this in favor of #45.
